networks:
  prodnetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
volumes:
  nexus-data:
  jenkins-data:
services:
  nexus:
    image: klo2k/nexus3
    restart: always
    ports:
      - "18081:8081"
    networks:
      prodnetwork:
        ipv4_address: 10.5.0.6
    volumes:
      - nexus-data:/nexus-data
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "18080:8080"
    networks:
      prodnetwork:
        ipv4_address: 10.5.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - nexus