unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: >
      pipelineJob('Sber-Test-CI') {
          definition {
              cpsScm {
                  scm {
                      github('znhv/sber_test')
                  }
              }
          }
          triggers {
            urlTrigger {
                url('http://10.5.0.1:18081/repository/pypi-internal/') {
                    status(202)
                }
            }
        }
      }
