unclassified:
   location:
     url: http://localhost:18080/

jobs:
  - script: >
      pipelineJob('Sber Test') {
        definition {
          cpsScm {
            scm {
                github('znhv/sber_test')
            }
          }
        }
        triggers {
          urlTrigger {
            cron('*/2 * * * *')
            url('http://10.5.0.1:18081/repository/pypi-internal/') {
                status(200)
                check('status')
            }
          }
        }
      }
