unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: >
      job("Git-CI") {
        scm {
          git {
            remote {
              url('https://github.com/znhv/sber_test.git')
            }
            extensions {
              cleanAfterCheckout()
            }
          }
        }
        triggers {
            scm('15/H * * * *')
            githubPush()
        }
      }