unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: >
      job("Sber-CI") {
        scm {
          github('github.com/znhv/sber_test', 'master')
        }
        triggers {
            cron('/2 * * * *')
        }
      }