unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/znhv/sber_test.git')
              }
          }
      }
  - file: ./jobdsl/job.groovy
#  - script: >
#      pipelineJob('product-job') {
#        definition {
#            pipelineJob('example') {
#            definition {
#                cps {
#                    script(readFileFromWorkspace('pipeline.groovy'))
#                    sandbox()
#                }
#            }
#          }
#        }
#      }