pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }

            steps {
                git branch: 'main', url: 'https://github.com/znhv/hello_world'
                sh 'python main.py'
            }

            post {
                success {
                    archiveArtifacts allowEmptyArchive: true,
                    artifacts: '*.py',
                    caseSensitive: false,
                    defaultExcludes: false,
                    followSymlinks: false,
                    onlyIfSuccessful: true
                }
            }
        }
        stage('publish to nexus') {
            steps {
                script {
                    nexusArtifactUploader(
                        nexusVersion: 'nexus3',
                        protocol: 'http',
                        nexusUrl: 'localhost:18081',
                        groupId: 'example',
                        version: '2.4',
                        repository: 'repository-example',
                        credentialsId: 'nexus-credentials',
                        artifacts: [
                            [artifactId: 'pytest',
                             classifier: '',
                             file: 'main.py',
                             type: 'py']
                        ]
                     );
                }
              }
            }
        }
    }